import { Quicksand} from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";
import { Toaster } from "react-hot-toast";



const quicksand =Quicksand({
  subsets:['latin']
});

export const metadata = {
  title: "Pet Adoption",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${quicksand.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-pink-50 ">
        <Navbar></Navbar>
        {children}
        <Toaster />
        <Footer></Footer>
        </body>
    </html>
  );
}
